# Generated by Django 5.0.8 on 2024-08-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature_C',
            field=models.IntegerField(),
        ),
    ]
