# Generated by Django 5.0.8 on 2024-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_alter_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
