# Generated by Django 5.0.8 on 2024-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
